# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  push:
    branches:
      - "release"

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          server-id: s02-02-uam-module-pojo # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: print variables
        run: echo "variables $GITHUB_WORKSPACE - ${{ vars.ACTION_USER }} - ${{ secrets.ACTION_SECRET }}"

      - name: java environment
        run: java --version

      - name: mvn environment
        run: mvn -v

      - name: Configure Maven
        uses: s4u/maven-settings-action@v3.1.0
        with:
          servers: |
            [{
                "id": "github-s01-core-service",
                "username": "${{ secrets.ACTION_USER }}",
                "password": "${{ secrets.ACTION_SECRET }}"
            }]

      - name: settings file
        run: cat ~/.m2/settings.xml

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Publish to GitHub Packages Apache Maven
        run: mvn deploy
        env:
          GITHUB_TOKEN: ${{ github.token }}
